### ISSUE TITLE
Missing /scripts folder

### ISSUE THREAD

**Issue by dusanvita** [patrickhoey/BludBourne#1]
Hello @patrickhoey,

I got the book from Amazon, and started reading, but after I cloned the source and tried to build it, found that /scripts folder with json files is missing. Will it maybe be mentioned later in the book, because I just started reading it and wanted to check out the game as soon as possible.

Thanks,
Dusan

**Comment by patrickhoey** [comment]
Hello Dusan,

The BludBourne project that I have here on GitHub is basically the final full project that you will end up with by the end of the book. You should be able to just clone and build. I just tested my local copy of the BludBourne repo, and I can build without any errors. 

If you are still having problems, please give me more specific error messages so I can try to figure out what problems you are having (a copy/paste of your standard out error messages). If you are using your own IDE (Not IDEA Community Edition) it could be issues with paths or the Gradle setup.

If you are following the book, then I recommend that you download the project archive that contains the source for each of the chapters. There are a few ways to get the zip file that contains the source chapter by chapter.

1) I just pushed a new repo to GitHub called MasteringLibGDXGameDevelopment_CodeBundle. This contains the zip files for each of the chapters, which in turn contain the source specific to the corresponding chapter. (https://github.com/patrickhoey/MasteringLibGDXGameDevelopment_CodeBundle)

2) Register here at https://www.packtpub.com/books/content/support and they will email you a link to the zip file that contains all source for the chapters in the book

3)  You can review the commit history log of the BludBourne project on GitHub, and look at the check-in comments. You can select the last comment that has the current chapter you are reviewing, such as "Ch02" and check that version out to your own private branch.

**Comment by dusanvita** [comment]
Thank you so much for the tips and most of all the fast response. This is the error I get when after successfully importing the project to AndroidStudio and using Application as a build configuration:

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationException: Error reading file: scripts/town_folk.json
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:683)
	at com.packtpub.libgdx.bludbourne.Entity.getEntityConfigs(Entity.java:187)
	at com.packtpub.libgdx.bludbourne.EntityFactory.<init>(EntityFactory.java:44)
	at com.packtpub.libgdx.bludbourne.EntityFactory.getInstance(EntityFactory.java:63)
	at com.packtpub.libgdx.bludbourne.screens.MainGameScreen.<init>(MainGameScreen.java:75)
	at com.packtpub.libgdx.bludbourne.BludBourne.create(BludBourne.java:59)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: com.badlogic.gdx.utils.SerializationException: Error parsing file: scripts/town_folk.json
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:77)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:681)
	... 7 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: scripts\town_folk.json (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
	at com.badlogic.gdx.files.FileHandle.reader(FileHandle.java:163)
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:75)
	... 8 more

After some time I have actually found the location of the scripts folder in core/assets/scripts, but I can't find why the error is occurring...

Again thank you so much for the tips, it makes a lot of sense, I will follow up by checking out chapter commits. Amazing job you did on organizing things, and so far in the book I find it very useful and understanding. Great job, thank you for that! :+1:

**Comment by patrickhoey** [comment]
I have not used Android Studio, but the issue sounds like it is using the root directory of the project as the working directory. Try setting the "working directory" to "core/assets". It should then be able to find all the resource files correctly.

**Comment by dusanvita** [comment]
Heads up, I made it work after editing the paths to be like:
core/assets/scripts/town_folk.json
instead of:
scripts/town_folk.json

Not sure if it's an issue in my project setup, still trying to figure how libGDX uses gradle.

**Comment by dusanvita** [comment]
Exactly, thanks for the support! :)
